# Generated by Django 4.0 on 2021-12-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Резерв', 'Reserve'), ('Оплачено', 'Paid'), ('Проведено', 'Carried Out'), ('Отменено', 'Canceled')], max_length=10)),
            ],
        ),
    ]
