# Generated by Django 4.0 on 2021-12-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='datatime',
            new_name='datetime',
        ),
    ]
